# .github/workflows/ci-build.yaml
name: CI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js (adjust version as needed)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Lint step
      - name: Run lint
        run: npm run lint

      # 5. Test step
      - name: Run tests
        run: npm test
