name: CI Build

on:
  push:
    branches:
      - main
  # You might also want to run this on pull requests
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use a recent version

      - name: Set up Python
        uses: actions/setup-python@v5 # Use a recent version
        with:
          python-version: '3.9' # Or your project's Python version (e.g., '3.10', '3.11')

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Install flake8 and any other development dependencies
          pip install flake8

      - name: Run Flake8 Linter
        run: |
          # Run flake8 on your project files
          # Adjust the path '.' if your code is in a subdirectory
          flake8 .

      # You can keep your original step or add others here
      - name: Print Build Success Message
        run: echo "CI Build and Linting ran successfully!"

      # Add your test step here later for Task 3
      # - name: Run Tests
      #   run: |
      #     # commands to run your tests (e.g., pytest, nose2)
      #     echo "Running tests (placeholder)"

      # Add steps for building, packaging, etc. if needed
